### ISSUE TITLE
Use Cmd-[Key] for cut, copy, paste on Mac

### ISSUE THREAD

**Issue by Maethil** [bubba0077/Trivia#103]
The client can sometimes lag when typing, so using an outside text editor can be preferable for transcribing questions. It would be good to be able to paste the completed questions in.

This is even more important for answers, since sometimes a wall of text needs to be copied from Google (e.g., "Give us every item from this list.").

**Comment by bubba0077** [comment]
I believe this is fixed, but I don't have a Mac with which to test it.

**Comment by bezthomas** [comment]
Looks like we need to reopen this one.
