### ISSUE TITLE
+1 button is pre-depressed

### ISSUE THREAD

**Issue by hemberger** [bubba0077/Trivia#108]
As a possible carry-over from previous rounds, the +1 button is sometimes pre-depressed.

Submitted for wthrowe.

**Comment by bubba0077** [comment]
I think this commit will take care of the issue.

**Comment by bubba0077** [comment]
On second thought, we are already leaving stale user names in answers for submitter/caller. The only difference about this would be that all the confidence buttons would reset when a user changed their name if we let a stale username stand here. If we propagate a username through, we could update update submitter/callers as well.
