### ISSUE TITLE
Changing answer sorting takes forever

### ISSUE THREAD

**Issue by hemberger** [bubba0077/Trivia#132]
Current testing (with 16 visible answers) shows that changing the sorting (by clicking on the arrow by Q#) takes over 20 seconds.

**Comment by bubba0077** [comment]
I noticed this too, I'll look into it tomorrow. I think the issue is responding to the click, not the sort part.

**Comment by bubba0077** [comment]
Previous assertion backed up by the fact that changing the sort via menu works fine.
