### ISSUE TITLE
Have to answer a billion dialogs to open the client

### ISSUE THREAD

**Issue by hemberger** [bubba0077/Trivia#134]
Even selecting "Always trust content from this publisher" when running the client with javaws, I get a billion dialogs saying:
```
Application __ from http://trivia.bgsh.org/ is missing the permissions attribute. Applications without this attribute should not be trusted. Do you wish to allow this application to run?
```
These dialogs show up *every* time the client is opened.
 * Is there a way to silence these messages?
 * Dealing with this issue may be a barrier for casual participants.

**Comment by bubba0077** [comment]
I made a new version using the correct manifest file. Let me know if that helps.

**Comment by hemberger** [comment]
I downloaded and ran using a newly downloaded jnlp, and I still got all the messages.

**Comment by bubba0077** [comment]
I will keep looking into this, but we might not be able to do anything about it without spending hundreds on a trusted certificate.

**Comment by hemberger** [comment]
Would we be able to consolidate the applications so that there is a single file that wraps them all? Then you would only get the dialog once.

**Comment by bubba0077** [comment]
I'm not sure I follow. Are you getting a warning on every single jar?

**Comment by hemberger** [comment]
I guess they're jars? I'm not going to type them all out, and I can't
copy+paste from the dialog, but many files are "-gfa".  The terminal output
shows:

```
This application does not specify a Codebase in its manifest. Please verify
with the applet's vendor. Continuing. See:
http://docs.oracle.com/javase/7/docs/technotes/guides/jweb/security/no_redeploy.html
for details.
Application title was not found in manifest. Check with application vendor
```

**Comment by bubba0077** [comment]
Alright, I'll look into doing something about that when I get home.

**Comment by bubba0077** [comment]
I've made a potential fix where I extract all of the 3rd-party jars and pack them into client jar. It would mean a larger download when the client is updated, but I don't think it will matter otherwise. I tried to just include the 3rd party jars in the client jar, but java wasn't able to import them from there for some reason.

Please download the new triviaClient.jnlp and test. You should only get one security pop-up.

**Comment by hemberger** [comment]
Everything is now in the triviaClient.jar, and I only get one security pop-up. That's fine with me!

**Comment by bubba0077** [comment]
That's as good as we'll be able to get without buying a trusted code certificate.
