### ISSUE TITLE
Lots of beeps at startup

### ISSUE THREAD

**Issue by hemberger** [bubba0077/Trivia#135]
Why do I get 4 beeps when the application starts? Seems excessively noisy.

**Comment by bubba0077** [comment]
Right now, each answer queue dings when it updates, so when the client starts you get each one dinging once on creation and again when it gets data. I can change it so that at least only "live" queues ding, and not the one on the history tab (which would make sense).

**Comment by hemberger** [comment]
Yeah, I'm just worried about when someone logs in while we're brute forcing some questions and there are a hundred answers in the queue :)

**Comment by bubba0077** [comment]
Well, there shouldn't be a beep for each answer when they are all loaded at once on startup.
