### ISSUE TITLE
Scroll sensitivity is really low

### ISSUE THREAD

**Issue by hemberger** [bubba0077/Trivia#145]
A full swipe of my scroll wheel only moves the window by about half the height of a proposed answer. Would be nice if it was much more sensitive.

**Comment by hemberger** [comment]
This seems to only (or primarily) apply to scrollbars in the Workflow window. Dialogs that pop up seem much more sensitive.

**Comment by hemberger** [comment]
The sensitivity in the Question element could also stand to be a bit faster.

**Comment by hemberger** [comment]
Low scroll sensitivity in the "By Round" tab.

**Comment by bubba0077** [comment]
Gonna try closing this again and hoping all the scrolls are good now.
