### ISSUE TITLE
"Treat seperate lines as multiple guesses" doesn't work #bug

### ISSUE THREAD

**Issue by AstroDocCarl** [bubba0077/Trivia#148]
If an answer is put on multiple lines and shift+enter is used to give a response it automatically treats them as seperate guesses even if the "treat seperate . . ." box isn't checked

**Comment by hemberger** [comment]
In principle this might actually be a good thing to happen automatically (since you have to mindfully shift+enter to get a new line). However, I could imagine it being a problem to happen automatically if you're copy+pasting answers from somewhere else.
