### ISSUE TITLE
There should be a way to mark an answer as accidental or something

### ISSUE THREAD

**Issue by wthrowe** [bubba0077/Trivia#150]
There should be a way to hide or mark an answer if you submit it to the wrong question or something.  If someone else submits the same answer your hiding should not prevent their answer from showing up.

**Comment by bubba0077** [comment]
Could we just overload duplicate for this?

**Comment by bubba0077** [comment]
Automatic duplicate checking now only marks as duplicate if the other answer is not marked as a duplicate. This means duplicate can serve as a status from mistake answers as well.
