### ISSUE TITLE
Any way to notify people that a question was closed or marked correct?

### ISSUE THREAD

**Issue by hemberger** [bubba0077/Trivia#153]
Currently, answers just disappear. I wonder if there's some way on the workflow tab to identify what just happened to the question? Would that even be useful?

**Comment by bubba0077** [comment]
Would sticking it in the status at the bottom be enough, or do we need something more obvious?

**Comment by hemberger** [comment]
That would probably be good enough for me, but that's because I'm also using a terminal, where statuses show up with permanence. I guess I'm also worried for people who aren't as familiar with the software.

**Comment by bubba0077** [comment]
I'm thinking add a string of numbers in the open question header on the right side that will show question numbers that have been opened, either green, red or white for correct/incorrect/open.

**Comment by hemberger** [comment]
That was actually along the lines of something I was thinking. Would be cool, but definitely lower priority.
