### ISSUE TITLE
Editing a question makes it momentarily disappear

### ISSUE THREAD

**Issue by hemberger** [bubba0077/Trivia#154]
Maybe this is due to the lag we're seeing at the moment, but when editing a question, it disappears long enough that it's not clear whether it was closed/answered/edited.

**Comment by bubba0077** [comment]
Definitely lag related, but that doesn't mean it can't be improved.

**Comment by bubba0077** [comment]
Should be solved by Commit 30633cea3059d82d28d6e115cdca501c81a99595
