### ISSUE TITLE
Automatically marking something as a duplicate obscures obviously correct answers

### ISSUE THREAD

**Issue by hemberger** [bubba0077/Trivia#155]
Perhaps proposed answers that are duplicates should automatically get +1's or something. I remember in the past that I would prioritize answers that lots of people were submitting. Automatically hiding them obscures this, and showing duplicates isn't a good alternative.

An auto +1 seems reasonable to me, if that's technologically feasible.

**Comment by bubba0077** [comment]
This should actually be fairly easy.
