### ISSUE TITLE
Rearrange Conf column items

### ISSUE THREAD

**Issue by hemberger** [bubba0077/Trivia#160]
In the Proposed Answer element, I suggest that the items in the Conf column be rearranged.

Instead of:

TL = confidence
TR = +1
BL = agreement
BR = -1

I think it would visually make a lot more sense if the four items were reordered to:

TL = confidence
TR = agreement
BL = +1
BR = -1

With this change, you see the confidence as (2 +1) instead of (2 \n +1). And with the +/-1 buttons on the same row, it will be clearer which answers you have agreed/disagreed with.

**Comment by bubba0077** [comment]
Want more feedback on this before making any changes.
