### ISSUE TITLE
Separator between Questions and Answers is confusing

### ISSUE THREAD

**Issue by hemberger** [bubba0077/Trivia#167]
When I mouse over the bottom of the separator, my mouse changes from the pointer to the "resize" skin. However, this is not where the resizing is done. You have to click on the middle of the separator, which is not identified as a resize element by the GUI.

**Comment by bubba0077** [comment]
This seems to be a problem with Java, so it would require rewriting the SplitPane class.

**Comment by hemberger** [comment]
I don't recall this being an issue before.

**Comment by bubba0077** [comment]
I didn't change anything...
