### ISSUE TITLE
Wiki page: info should be in column on left side of page

### ISSUE THREAD

**Issue by hemberger** [bubba0077/Trivia#171]
On the wiki page, the header image is very large, which causes the info column on the right side to be cut off on browsers that aren't full screen width. This causes confusion for new players who are looking for the info (since horizontal scrolling isn't always obvious).

If the info column were on the left side, this potential problem would be eliminated.

**Comment by bubba0077** [comment]
The google sites management is a little wonky, but I managed to be able to get the sidebar to appear even at much narrower width now.
