### ISSUE TITLE
There should be a way to list used visual trivia

### ISSUE THREAD

**Issue by wthrowe** [bubba0077/Trivia#186]

**Comment by hemberger** [comment]
This is a good idea, but we'll need some way to ensure the Facebook visual trivia aren't marked as regular visual trivia (which was a confusing problem this year, since Facebook visual trivia was new this year).

**Comment by bubba0077** [comment]
I think we should be calling those FB Trivia so they don't get marked as Visual Trivia to begin with.

**Comment by Maethil** [comment]
Could this change be implemented in the website instead of the client, perhaps?
