### ISSUE TITLE
Cursor doesn't accurately indicate position when typing

### ISSUE THREAD

**Issue by Maethil** [bubba0077/Trivia#189]
Toward the end of a long question, the cursor seems to get somewhat offset from where it's supposed to be in the text -- e.g., if you clicked between the "g" and "e" in "roger", it would look like it's between the "g" and "e" but would actually be positioned between the "o" and "g".

This is on my Mac with Java 7 Update 75, and is really not that big a deal.

**Comment by bubba0077** [comment]
Cannot reproduce.
