### ISSUE TITLE
Add README for setup help

### ISSUE THREAD

**Issue by hemberger** [bubba0077/Trivia#197]
I remember all the software I needed last year to get things up and running, but now that a year has passed, I mostly forget. I'm on Linux. Did I just need openjdk and javaws? It would be useful to have a README to keep track of this info for future years and new users.

**Comment by bubba0077** [comment]
I don't know that a README would be effective here, since the majority will never look at the repository.

**Comment by hemberger** [comment]
It would have helped me know that openjdk 8 was needed.

**Comment by bubba0077** [comment]
Well if you had read the e-mail ;)  (j/k, file added)
