### ISSUE TITLE
Menu selections throw java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by wthrowe** [bubba0077/Trivia#211]

**Comment by wthrowe** [comment]
Changing role does as well.  I'm guessing these are related.

**Comment by wthrowe** [comment]
Actually, it seems that almost any menu selection causes this.  Changing roles, changing names, changing filter settings.  Not the stuff in the External menu, though.

**Comment by bubba0077** [comment]
I suspect this isn't the menus, but something going on with the updating of the user list.

**Comment by bubba0077** [comment]
These seem to have gone away since the fixing of Issue #204, so it was likely related to that.
