### ISSUE TITLE
New tab button jumps areound with many tabs

### ISSUE THREAD

**Issue by wthrowe** [bubba0077/Trivia#213]
If the tab list takes up multiple lines the new tab button jumps around when switching tabs.

Also, if it happens to jump to the location of the tab you just selected the new tab window pops up.

**Comment by bubba0077** [comment]
I tried this out, and the new tab always stays next to the same tab, even as they change rows. The new tab only changes rows if you click on a tab in a different level, then the tab rows swap. AFAIK this is standard behavior of tabbed panes with multiple rows. Even if I wanted to always keep the new tab button on the same row, it would be too much effort for too little benefit.
